name: "Publish"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # This step is required as we need to get file details
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # Debug step to validate markdown file
      - name: Validate markdown file
        run: |
          echo "Creating ultra-minimal test file"
          cat > ./post/blog/simple-post.md << 'EOF'
          ---
          title: "Test Post"
          publish: true
          description: Simple test
          tags:
            - test
          enableTableOfContent: false
          isNewsletterActivated: false
          ---

          # Hello Hashnode

          This is a minimal test post.
          EOF
          
          echo "Simple post content:"
          cat ./post/blog/simple-post.md
      
      # Try to capture error details
      - name: Debug HASHNODE_KEY
        run: |
          if [ -n "${{ secrets.HASHNODE_KEY }}" ]; then
            echo "HASHNODE_KEY is set (displaying first 4 chars): ${HASHNODE_KEY:0:4}..."
          else
            echo "HASHNODE_KEY is not set or empty"
          fi
        env:
          HASHNODE_KEY: ${{ secrets.HASHNODE_KEY }}
       
      # The action which publish the blog
      - name: Publish to Hashnode
        # note: using @v2 (current latest version)
        uses: raunakgurud09/hashnode-publish@v2
        id: publish_hashnode
        with:
          hashnode_key: ${{ secrets.HASHNODE_KEY }}
          file: "./post/blog/simple-post.md"
          host: "balrajsingh.hashnode.dev"
        continue-on-error: true
      
      # Get detailed error info
      - name: Get detailed output
        run: |
          echo "Result JSON: ${{steps.publish_hashnode.outputs.result_json}}"
          echo "Summary: ${{steps.publish_hashnode.outputs.result_summary}}"
          echo "Outcome: ${{steps.publish_hashnode.outcome}}"
        if: always()

