name: "Publish"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use the latest version of the checkout action
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
      - name: Validate Markdown File
        run: |
          echo "Validating markdown file structure..."
          if [ -f "./post/blog/AboutThisProject.md" ]; then
            echo "Markdown file exists, checking frontmatter..."
          else
            echo "::error::Markdown file not found at ./post/blog/AboutThisProject.md"
            exit 1
          fi
      
      # The action which publish the blog
      - name: Publish to Hashnode
        uses: raunakgurud09/hashnode-publish@v2
        id: publish_hashnode
        with:
          hashnode_key: ${{ secrets.HASHNODE_KEY }}
          file: "./post/blog/AboutThisProject.md"
          host: "balrajsingh.hashnode.dev"
        continue-on-error: true
        
      - name: Check Publishing Result
        run: |
          if [[ "${{steps.publish_hashnode.outcome}}" == "success" ]]; then
            echo "Successfully published to Hashnode!"
            echo "${{steps.publish_hashnode.outputs.result_json}}"
          else
            echo "::warning::Failed to publish to Hashnode. Please check your API key and content format."
            echo "If the issue persists, try publishing manually or contact Hashnode support."
          fi

